accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Login, Signup, Logout

app_name="accounts"
urlpatterns = [
	path('login/', Login, name='login'),
	path('signup/', Signup, name='signup'),
	path('logout/', Logout, name='logout'),
]

producthunt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home, ProductCreateView, ProductDetailView, Upvote


app_name="products"
urlpatterns = [
    path('', Home, name='home'),
    path('create/', ProductCreateView, name='product-create'),
    path('detail/<int:product_id>/', ProductDetailView, name='product-detail'),
    path('detail/<int:product_id>/', ProductDetailView, name='product-detail'),
    path('upvote/<int:product_id>/', Upvote, name='upvote'),


 
]

accounts/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
	title 		= models.CharField(max_length=255)
	url			= models.TextField()
	pub_date 	= models.DateTimeField()
	votes_total = models.IntegerField(default=1)
	image 		= models.ImageField(upload_to='images/')
	icon		= models.ImageField(upload_to='images/')
	body 		= models.TextField()
	#hunter is a foreign key to the model User #
	#on_delete refer to what happens if the user is deleted (delete product or not)
	hunter 		= models.ForeignKey(User, on_delete=models.CASCADE)

	def pub_date_pretty(self):
		return self.pub_date.strftime('%b %e %Y')

	def __str__(self):
		return self.title

	def summary(self):
		return self.body[:100]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
def Login(request):
	if request.method == 'POST':
		user = auth.authenticate(username=request.POST["username"],password=request.POST["password"])
		if user is not None:
			auth.login(request,user)
			return HttpResponseRedirect(reverse('products:home'))
		else: 
			return render(request,'accounts/login.html', {'error': 'Credentials are incorrect!'})



	else:
		return render(request,'accounts/login.html')

def Signup(request):
	if request.method=='POST':
		#if the user enter infos
		if request.POST["password1"] == request.POST["password2"]:
			try:
				user = User.objects.get(username=request.POST["username"])
				return render(request,'accounts/signup.html', {'error': 'Username taken!'})
			except User.DoesNotExist:
				user = User.objects.create_user(username=request.POST["username"], password=request.POST["password1"])
				auth.login(request,user)
				return HttpResponseRedirect(reverse('products:home'))
		else:
			return render(request,'accounts/signup.html', {'error': 'Passwords not matching'})



	else:
		#if the user wans to register
		return render(request,'accounts/signup.html')

def Logout(request):
	if request.method == 'POST':
		auth.logout(request)
		return HttpResponseRedirect(reverse('products:home'))

	return render(request,'accounts/signup.html')

products/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import HttpResponseRedirect
from .models import Product

# Create your views here.
def Home(request):
	products = Product.objects.all()

	return render(request,'products/home.html', {'product_list':products})

@login_required(login_url="/accounts/signup")
def ProductCreateView(request):
	if request.method=='POST':
		if request.POST["title"] and request.POST["body"] and request.POST["url"] and request.FILES["icon"] and request.FILES["image"]:
			product = Product()
			product.title = request.POST["title"]
			product.body = request.POST["body"]

			if request.POST["url"].startswith('http://') or request.POST["url"].startswith('https://'):
				product.url = request.POST["url"]

			else:
				product.url = 'http://' + request.POST["url"]
			
			product.icon = request.FILES["icon"]
			product.image = request.FILES["image"]
			product.pub_date= timezone.datetime.now()
			product.hunter=request.user
			product.save()
			return HttpResponseRedirect('/detail/' + str(product.id))

		else:
			return render(request,'products/product_create.html', {'error': 'All the fields are required'})
		

	return render(request,'products/product_create.html')

@login_required
def ProductDetailView(request, product_id):
	product = get_object_or_404(Product, pk=product_id)
	return render(request,'products/product_detail.html',{'instance':product})

@login_required(login_url="/accounts/signup")
def Upvote(request, product_id):
	if request.method=='POST':

		product = get_object_or_404(Product, pk=product_id)
		product.votes_total += 1
		product.save()
	return HttpResponseRedirect('/detail/' + str(product.id))

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<h1> Login!</h1>
<form method="POST" action="{% url 'accounts:login' %}">{% csrf_token %}

Username :<br />
<input type='text' name="username"/>
<br />
Password :<br />
<input type='password' name="password"/>

<br /><br />
<input class="btn btn-primary" type='submit' value="Login"/>
</form>	
{% if error %}
{{error}}
<br />
<br />
{% endif %}
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Sign Up!</h1>
<form method="POST" action="{% url 'accounts:signup' %}">{% csrf_token %}

Username :<br />
<input type='text' name="username"/>
<br />
Password :<br />
<input type='password' name="password1"/>
<br />
Confirm Password :<br />
<input type='password' name="password2"/>
<br /><br />
<input class="btn btn-primary" type='submit' value="Join us!"/>
</form>	
{% if error %}
{{error}}
<br />
<br />
{% endif %}
{% endblock content %}

producthunt/templates/base.html
<!doctype html>
<html lang="en">

  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Product Hunt</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
    <header>
        
    	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
    		<a class="navbar-brand" href="{% url 'products:home' %}">
            <img src="{% static 'logo.png' %}" class="d-inline-block alighn-top" height="30" width="30" />
            Product Hunt
            </a>
    		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
    		</button>
    		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    			<div class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}

                     <a class="nav-item nav-link" href="{% url 'products:product-create' %}">
                    <button type="button" class="btn btn-success">Create a Product</button></a>&nbsp; &nbsp;
                     <!--  document.getElementById('logout').submit() whenever the user clicks on logout the form is called-->
                    <a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}"><p>LOGOUT</p></a>
                    <!--  logout must be done with a POST method to not interfer with navigator auto calls-->
                    <form id='logout' method='POST' action="{% url 'accounts:logout' %}">
                        {% csrf_token %}
                        <input type="hidden"/>
                    </form>
    				
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">LOGIN</a>

                    {% endif %}
    				
    			</div>
    		</div>
            </div>
    	</nav>
    
  
	</header>



    <div class="container">
{% block content %}
{% endblock content %}

    </div>



    <footer class="text-muted">
  <div class="container text-center">
    <p> &copy; Badreddine Bidouli {% now "Y" %}</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script></body>
</html>

products/templates/products/home.html
{% extends 'base.html' %}

{% block content %}
{% for instance in product_list %}

<div class="row pt-3">
<div class="col-2" onclick="window.location='{% url 'products:product-detail' instance.id %}';" style="cursor:pointer;">
	<img src="{{instance.icon.url}}" class="img-fluid" />
</div>
<div class="col-6" onclick="window.location='{% url 'products:product-detail' instance.id %}';" style="cursor:pointer;">

	<h1>{{instance.title}}</h1>
	<p>{{instance.summary}}</p>
</div>
<div class="col-4">
	<a href="javascript:{document.getElementById('upvote{{instance.id}}').submit()}"><button class="btn btn-primary btn-lg btn-block">Upvote +{{instance.votes_total}}!</button></a>
</div>
</div>

<form id="upvote{{instance.id}}" method="POST" action="{% url 'products:upvote' instance.id %}">
	{% csrf_token %}
	<input type="hidden">
</form>

{% endfor %}
{% endblock content %}

products/templates/products/product_create.html
{% extends 'base.html' %}

{% block content %}

<h1>Create a product</h1>
<p>Start creating your product now!</p>
<form method="POST" action="{% url 'products:product-create' %}" enctype="multipart/form-data">{% csrf_token %}

Title :<br />
<input type='text' name="title"/>
<br />
Body :<br />
<input type='text' name="body"/>
<br />
URL :<br />
<input type='text' name="url"/>
<br />

Icon :<br />
<input type='file' name="icon"/>
<br />
Image :<br />
<input type='file' name="image"/>
<br />

<br />
<input class="btn btn-primary" type='submit' value="Hunt!"/>
</form>	
{% if error %}
{{error}}
<br />

{% endif %}
{% endblock content %}

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<br/>


<div class="row">
	<div class="col-2">
		<img src="{{instance.icon.url}}"  height="60" width="60" class="img-fluid">
	</div>
	<div class="col-6 text-right" >
		<a href="{{instance.url}}"><h1>{{instance.title}}</h1></a>
	</div>
</div>
<br/>
<div class="row">
	<div class="col-8">
		<img src="{{instance.image.url}}" class="img-fluid" />
	</div>
	<div class="col-4">
		<a href="javascript:{document.getElementById('upvote').submit()}"><button class="btn btn-primary btn-lg btn-block">Upvote +{{instance.votes_total}}!</button></a>
	</div>
</div>

<div class="row">
	<div class="col-4">
		<h4>Hunted by {{instance.hunter.username}}</h4>
	</div>
	<div class="col-4 text-right">
		<h4> {{instance.pub_date_pretty}}</h4>
	</div>
</div>

<div class="row">
	<div class="col-8">
		<p>{{instance.body}}</p>
	</div>
	
</div>
<form id="upvote" method="POST" action="{% url 'products:upvote' instance.id %}">
	{% csrf_token %}
	<input type="hidden">
</form>

<br />

{% if error %}
{{error}}
<br />

{% endif %}
{% endblock content %}